#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: immortalwrt-23

on:
  push:
    branches:
      - main
    paths:
      - 'immortalwrt-23/.config'
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt.git
  REPO_BRANCH: openwrt-23.05
  FEEDS_CONF: immortalwrt-23/feeds.conf.default
  CONFIG_FILE: immortalwrt-23/.config
  DIY_P1_SH: immortalwrt-23/diy1.sh
  DIY_P2_SH: immortalwrt-23/diy2.sh
  UPLOAD_FIRMWARE: false
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Ê£ÄÊü•È°πÁõÆÂàÜÊîØ
      uses: actions/checkout@main

    - name: ÂàùÂßãÂåñÁºñËØëÁéØÂ¢É
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo apt update
        sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)'
        sudo apt autoremove --purge
        sudo apt clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        echo "FIRMWARE_VERSION=$(date +"%y%m%d")" >> $GITHUB_ENV
        echo "START_DATE=$(date +%s)" >> $GITHUB_ENV

    - name: ‰∏ãËΩΩÊ∫êÁ†Å
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone --single-branch -b $REPO_BRANCH $REPO_URL openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: Âä†ËΩΩËΩØ‰ª∂Ê∫ê
      run: |
        [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
        chmod +x $DIY_P1_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P1_SH

    - name: Êõ¥Êñ∞Âπ∂ÂÆâË£ÖËΩØ‰ª∂Ê∫ê
      run: cd openwrt && ./scripts/feeds update -a && ./scripts/feeds install -a

    - name: Âä†ËΩΩËá™ÂÆö‰πâÈÖçÁΩÆ
      run: |
        [ -e immortalwrt-23/files ] && mv immortalwrt-23/files openwrt/files
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x $DIY_P2_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P2_SH

    - name: ‰∏ãËΩΩÂåÖ
      id: package
      run: |
        cd openwrt
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: ÁºñËØëÂõ∫‰ª∂
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Êï¥ÁêÜÊñá‰ª∂
      id: organize
      if: steps.compile.outputs.status == 'success' && !cancelled()
      run: |
        # Êï¥ÁêÜÂõ∫‰ª∂ÂåÖÊó∂ÂÄô,Âà†Èô§ÊÇ®‰∏çÊÉ≥Ë¶ÅÁöÑÂõ∫‰ª∂ÊàñËÄÖÊñá‰ª∂,ËÆ©ÂÆÉ‰∏çÈúÄË¶Å‰∏ä‰º†Âà∞ActionsÁ©∫Èó¥
        cd openwrt/bin/targets/*/*
        mkdir -p package
        mv packages package/core
        mv package packages
        mv $GITHUB_WORKSPACE/openwrt/bin/packages/*/* packages
        tar -czf packages.tar.gz packages
        rm -rf packages
        rm -rf version.buildinfo
        rm -rf profiles.json
        # rm -rf *rootfs*
        rm -rf *kernel*
        rm -rf *.manifest
        rm -rf feeds.buildinfo
        rm -rf sha256sums
        for file in immortalwrt*; do
          mv "$file" "${file/immortalwrt/immortalwrt-23-${{ env.FIRMWARE_VERSION }}}"
        done
        echo -e "$(sha256sum *)\n" > sha256sums
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: ‰∏ä‰º†Âõ∫‰ª∂Âà∞Github ActionsÁ©∫Èó¥
      if: steps.organize.outputs.status == 'success' && env.UPLOAD_FIRMWARE == 'true'
      uses: actions/upload-artifact@main
      with:
        name: immortalwrt-23-${{ env.FIRMWARE_VERSION }}
        path: ${{ env.FIRMWARE }}

    - name: Âà†Èô§ÊóßÁöÑRelease
      if: steps.organize.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.ACCOUNTS_JSON }}
        TAG_NAME: immortalwrt-23
      run: |
        RELEASE_URL="https://api.github.com/repos/${{ github.repository }}/releases/tags/$TAG_NAME"
        RELEASE_ID=$(curl -s -H "Authorization: token $GITHUB_TOKEN" $RELEASE_URL | jq -r '.id')
        if [ "$RELEASE_ID" != "null" ]; then
          echo "üóëÔ∏è Âà†Èô§Release‰∏≠: $RELEASE_ID..."
          curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID"
          echo "‚úÖ ReleaseÂà†Èô§ÊàêÂäü!"
        else
          echo "‚ö†Ô∏è Êú™ÊâæÂà∞tagÁöÑRelease: $TAG_NAME"
        fi

    - name: ÂàõÂª∫releaseÊ†áÁ≠æ
      id: tag
      if: steps.organize.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        echo "ÁºñËØëÊó∂Èó¥Ôºö$(date -d "@${{ env.START_DATE }}" +"%YÂπ¥%mÊúà%dÊó• %HÁÇπ%MÂàÜ")" >> release.txt
         echo "ÈªòËÆ§ÁΩëÂÖ≥Ôºö192.168.3.1" >> release.txt
        echo ÂåÖÂê´Êèí‰ª∂Ôºö$(grep "CONFIG_PACKAGE_luci-app-\(.*\)=y" openwrt/.config | sed "s/CONFIG_PACKAGE_luci-app-\(.*\)=y/\1/g" | grep -v "_\|arpbind\|autoreboot\|firewall\|opkg") >> release.txt
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Â∞ÜÂõ∫‰ª∂‰∏ä‰º†Âà∞release
      uses: softprops/action-gh-release@v1
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: upload-release
      with:
        name: immortalwrt-23-${{ env.FIRMWARE_VERSION }}
        tag_name: immortalwrt-23
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*

  
